sudo: required
language: cpp
dist: trusty

before_install:
  - # if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qq libboost-dev; fi
  - if [ "$TRAVIS_OS_NAME" =   "osx" ]; then brew update; brew upgrade python; fi

compiler:
  - gcc
  - clang

script:
  - cmake --version && python3 --version && cmake -G "Unix Makefiles" && make

os:
  - linux
  # - osx
