#!/usr/bin/env python
#
# Beautiful Capi generates beautiful C API wrappers for your C++ classes
# Copyright (C) 2015 Petr Petrovich Petrov
#
# This file is part of Beautiful Capi.
#
# Beautiful Capi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Beautiful Capi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Beautiful Capi.  If not, see <http://www.gnu.org/licenses/>.
#


class FileGenerator(object):
    def __init__(self, filename):
        self.file = open(filename, 'w')
        self.cur_indent = 0

    def increase_indent(self):
        self.cur_indent += 4

    def decrease_indent(self):
        self.cur_indent -= 4
        if self.cur_indent < 0:
            raise IndentationError

    def get_indent_str(self):
        return ' ' * self.cur_indent

    def put_line(self, line, eol='\n'):
        self.file.write(self.get_indent_str() + line + eol)

    def put_python_header(self):
        self.put_line('#!/usr/bin/env python')

    def put_gnu_gpl_copyright_header(self, empty_lines=True):
        self.put_line('#')
        self.put_line('# Beautiful Capi generates beautiful C API wrappers for your C++ classes')
        self.put_line('# Copyright (C) 2015 Petr Petrovich Petrov')
        self.put_line('#')
        self.put_line('# This file is part of Beautiful Capi.')
        self.put_line('#')
        self.put_line('# Beautiful Capi is free software: you can redistribute it and/or modify')
        self.put_line('# it under the terms of the GNU General Public License as published by')
        self.put_line('# the Free Software Foundation, either version 3 of the License, or')
        self.put_line('# (at your option) any later version.')
        self.put_line('#')
        self.put_line('# Beautiful Capi is distributed in the hope that it will be useful,')
        self.put_line('# but WITHOUT ANY WARRANTY; without even the implied warranty of')
        self.put_line('# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the')
        self.put_line('# GNU General Public License for more details.')
        self.put_line('#')
        self.put_line('# You should have received a copy of the GNU General Public License')
        self.put_line('# along with Beautiful Capi.  If not, see <http://www.gnu.org/licenses/>.')
        self.put_line('#')
        if empty_lines:
            self.put_line('')
            self.put_line('')

    def put_automatic_generation_warning(self, empty_lines=True):
        self.put_line('#')
        self.put_line('# WARNING: This file was automatically generated by Xsd2Python3.py program!')
        self.put_line('# Do not edit this file! Please edit the source XSD schema.')
        self.put_line('#')
        if empty_lines:
            self.put_line('')
            self.put_line('')


class Indent(object):
    def __init__(self, file_generator):
        self.file_generator = file_generator

    def __enter__(self):
        self.file_generator.increase_indent()

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.file_generator.decrease_indent()
