#!/usr/bin/env python
#
# Beautiful Capi generates beautiful C API wrappers for your C++ classes
# Copyright (C) 2015 Petr Petrovich Petrov
#
# This file is part of Beautiful Capi.
#
# Beautiful Capi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Beautiful Capi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Beautiful Capi.  If not, see <http://www.gnu.org/licenses/>.
#


#
# WARNING: This file was automatically generated by Xsd2Python3.py program!
# Do not edit this file! Please edit the source XSD schema.
#


from enum import Enum


def string_to_bool(string_value):
    return string_value.lower() in ["true", "on", "yes", "1"]


class TExceptionHandlingMode(Enum):
    no_handling = 0
    by_first_argument = 1

    @staticmethod
    def load(value):
        if value == "no_handling":
            return TExceptionHandlingMode.no_handling
        if value == "by_first_argument":
            return TExceptionHandlingMode.by_first_argument
        raise ValueError


class TBeautifulCapiParams(object):
    def __init__(self):
        self.folder_per_namespace = True
        self.file_per_class = True
        self.namespace_header_at_parent_folder = True
        self.generate_single_file = False
        self.single_header_name = "Output.h"
        self.dynamically_load_functions = False
        self.capi_header_suffix = "Capi"
        self.fwd_header_suffix = "Fwd"
        self.wrapper_class_suffix_copy_semantic = ""
        self.wrapper_class_suffix_reference_counted = "Ptr"
        self.wrapper_class_suffix_raw_pointer = "RawPtr"
        self.forward_typedef_suffix = "FwdPtr"
        self.is_null_method = "IsNull"
        self.is_not_null_method = "IsNotNull"
        self.delete_method = "Delete"
        self.forward_holder_filename = "beautiful_capi/forward_holder.h"
        self.check_and_throw_exception_filename = "beautiful_capi/check_and_throw_exception.h"
        self.exception_handling_mode = TExceptionHandlingMode.no_handling
        self.copyright_header = ""
        self.automatic_generated_warning = ""
    
    def load(self, dom_node):
        for element in [node for node in dom_node.childNodes if node.nodeName == "copyright_header"]:
            for text in [text for text in element.childNodes if text.nodeType == text.TEXT_NODE]:
                self.copyright_header += text.nodeValue
        for element in [node for node in dom_node.childNodes if node.nodeName == "automatic_generated_warning"]:
            for text in [text for text in element.childNodes if text.nodeType == text.TEXT_NODE]:
                self.automatic_generated_warning += text.nodeValue
        if dom_node.hasAttribute("folder_per_namespace"):
            cur_attr = dom_node.getAttribute("folder_per_namespace")
            self.folder_per_namespace = string_to_bool(cur_attr)
        if dom_node.hasAttribute("file_per_class"):
            cur_attr = dom_node.getAttribute("file_per_class")
            self.file_per_class = string_to_bool(cur_attr)
        if dom_node.hasAttribute("namespace_header_at_parent_folder"):
            cur_attr = dom_node.getAttribute("namespace_header_at_parent_folder")
            self.namespace_header_at_parent_folder = string_to_bool(cur_attr)
        if dom_node.hasAttribute("generate_single_file"):
            cur_attr = dom_node.getAttribute("generate_single_file")
            self.generate_single_file = string_to_bool(cur_attr)
        if dom_node.hasAttribute("single_header_name"):
            cur_attr = dom_node.getAttribute("single_header_name")
            self.single_header_name = cur_attr
        if dom_node.hasAttribute("dynamically_load_functions"):
            cur_attr = dom_node.getAttribute("dynamically_load_functions")
            self.dynamically_load_functions = string_to_bool(cur_attr)
        if dom_node.hasAttribute("capi_header_suffix"):
            cur_attr = dom_node.getAttribute("capi_header_suffix")
            self.capi_header_suffix = cur_attr
        if dom_node.hasAttribute("fwd_header_suffix"):
            cur_attr = dom_node.getAttribute("fwd_header_suffix")
            self.fwd_header_suffix = cur_attr
        if dom_node.hasAttribute("wrapper_class_suffix_copy_semantic"):
            cur_attr = dom_node.getAttribute("wrapper_class_suffix_copy_semantic")
            self.wrapper_class_suffix_copy_semantic = cur_attr
        if dom_node.hasAttribute("wrapper_class_suffix_reference_counted"):
            cur_attr = dom_node.getAttribute("wrapper_class_suffix_reference_counted")
            self.wrapper_class_suffix_reference_counted = cur_attr
        if dom_node.hasAttribute("wrapper_class_suffix_raw_pointer"):
            cur_attr = dom_node.getAttribute("wrapper_class_suffix_raw_pointer")
            self.wrapper_class_suffix_raw_pointer = cur_attr
        if dom_node.hasAttribute("forward_typedef_suffix"):
            cur_attr = dom_node.getAttribute("forward_typedef_suffix")
            self.forward_typedef_suffix = cur_attr
        if dom_node.hasAttribute("is_null_method"):
            cur_attr = dom_node.getAttribute("is_null_method")
            self.is_null_method = cur_attr
        if dom_node.hasAttribute("is_not_null_method"):
            cur_attr = dom_node.getAttribute("is_not_null_method")
            self.is_not_null_method = cur_attr
        if dom_node.hasAttribute("delete_method"):
            cur_attr = dom_node.getAttribute("delete_method")
            self.delete_method = cur_attr
        if dom_node.hasAttribute("forward_holder_filename"):
            cur_attr = dom_node.getAttribute("forward_holder_filename")
            self.forward_holder_filename = cur_attr
        if dom_node.hasAttribute("check_and_throw_exception_filename"):
            cur_attr = dom_node.getAttribute("check_and_throw_exception_filename")
            self.check_and_throw_exception_filename = cur_attr
        if dom_node.hasAttribute("exception_handling_mode"):
            cur_attr = dom_node.getAttribute("exception_handling_mode")
            self.exception_handling_mode = TExceptionHandlingMode.load(cur_attr)
    

def load(dom_node):
    """

    :rtype: TBeautifulCapiParams
    """
    for root_element in [root for root in dom_node.childNodes if root.localName == "params"]:
        root_params = TBeautifulCapiParams()
        root_params.load(root_element)
        return root_params
